var res = {
    // startLoading_json : "res/startLoading.json",
    start_json : "res/start.json",
    // main_json : "res/main_scene.json",
    // about_json : "res/about.json",
    // binding_json : "res/binding.json",
    alert_json : "res/alert.json",
    fish_json : "res/fish_machine.json",
    commonTop_json : "res/common_top.json",
    chat_json : "res/chat.json",
    userAlert_json : "res/userAlert.json",
    exchange_json : "res/exchange.json",
    // charge_json : "res/chargeAlert.json",
    // quitAlert_json : "res/quitAlert.json",
    
    ani_shayu_json : "res/ani/shayu.ExportJson",
    ani_shayu_plist : "res/ani/shayu0.plist",
    ani_shayu_png : "res/ani/shayu0.png",

    ani_moguiyu_json : "res/ani/moguiyu.ExportJson",
    ani_moguiyu_plist : "res/ani/moguiyu0.plist",
    ani_moguiyu_png : "res/ani/moguiyu0.png",
    
    ani_denglongyu_json : "res/ani/denglongyu.ExportJson",
    ani_denglongyu_plist : "res/ani/denglongyu0.plist",
    ani_denglongyu_png : "res/ani/denglongyu0.png",
    
    ani_wugui_json : "res/ani/wugui.ExportJson",
    ani_wugui_plist : "res/ani/wugui0.plist",
    ani_wugui_png : "res/ani/wugui0.png",
    
    ani_gold_json : "res/ani/gold.ExportJson",
    ani_gold_plist : "res/ani/gold0.plist",
    ani_gold_png : "res/ani/gold0.png",

    // game1 : "res/picture/game01.png",
    // game2 : "res/picture/game02.png",
    // game3 : "res/picture/game03.png",
    empty : "res/picture/empty.png",
    guang : "res/qietu/start/guang.png",
    bo : "res/qietu/fish/bo.png",
    light : "res/qietu/fish/shan.png",
    equip2 : "res/qietu/fish/equip_2.png",
    equip3 : "res/qietu/fish/equip_3.png",
    equip4 : "res/qietu/fish/equip_4.png",

    v0 : "res/qietu/user/v0.png",
    v1 : "res/qietu/user/v1.png",
    v2 : "res/qietu/user/v2.png",
    v3 : "res/qietu/user/v3.png",
    v4 : "res/qietu/user/v4.png",
    v5 : "res/qietu/user/v5.png",
    v6 : "res/qietu/user/v6.png",
    v7 : "res/qietu/user/v7.png",
    v8 : "res/qietu/user/v8.png",
    v9 : "res/qietu/user/v9.png",
    v10 : "res/qietu/user/v10.png",
    v11 : "res/qietu/user/v11.png",
    v12 : "res/qietu/user/v12.png",
    v13 : "res/qietu/user/v13.png",
    v14 : "res/qietu/user/v14.png",
    v15 : "res/qietu/user/v15.png",
    v16 : "res/qietu/user/v16.png",
    v17 : "res/qietu/user/v17.png",
    v18 : "res/qietu/user/v18.png",
    v19 : "res/qietu/user/v19.png",
    v20 : "res/qietu/user/v20.png",
    v21 : "res/qietu/user/v21.png",
    v22 : "res/qietu/user/v22.png",
    v23 : "res/qietu/user/v23.png",
    v24 : "res/qietu/user/v24.png",
    v25 : "res/qietu/user/v25.png",
    v26 : "res/qietu/user/v26.png",
    v27 : "res/qietu/user/v27.png",
    v28 : "res/qietu/user/v28.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
