var res = {
    startLoading_json : "res/startLoading.json",
    start_json : "res/start.json",
    main_json : "res/main_scene.json",
    about_json : "res/about.json",
    binding_json : "res/binding.json",
    alert_json : "res/alert.json",
    fish_json : "res/fish_machine.json",
    commonTop_json : "res/common_top.json",
    chat_json : "res/chat.json",

    game1 : "res/picture/game01.png",
    game2 : "res/picture/game02.png",
    game3 : "res/picture/game03.png",
    empty : "res/picture/empty.png",
    
    v0 : "res/qietu/user/v0.png",
    v1 : "res/qietu/user/v1.png",
    v2 : "res/qietu/user/v2.png",
    v3 : "res/qietu/user/v3.png",
    v4 : "res/qietu/user/v4.png",
    v5 : "res/qietu/user/v5.png",
    v6 : "res/qietu/user/v6.png",
    v7 : "res/qietu/user/v7.png",
    v8 : "res/qietu/user/v8.png",
    v9 : "res/qietu/user/v9.png",
    v10 : "res/qietu/user/v10.png",
    v11 : "res/qietu/user/v11.png",
    v12 : "res/qietu/user/v12.png",
    v13 : "res/qietu/user/v13.png",
    v14 : "res/qietu/user/v14.png",
    v15 : "res/qietu/user/v15.png",
    v16 : "res/qietu/user/v16.png",
    v17 : "res/qietu/user/v17.png",
    v18 : "res/qietu/user/v18.png",
    v19 : "res/qietu/user/v19.png",
    v20 : "res/qietu/user/v20.png",
    v21 : "res/qietu/user/v21.png",
    v22 : "res/qietu/user/v22.png",
    v23 : "res/qietu/user/v23.png",
    v24 : "res/qietu/user/v24.png",
    v25 : "res/qietu/user/v25.png",
    v26 : "res/qietu/user/v26.png",
    v27 : "res/qietu/user/v27.png",
    v28 : "res/qietu/user/v28.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
